server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: turnos-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/turnos/**
          filters:
            - StripPrefix=1

        - id: login-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*" 